### ISSUE TITLE
Ik zie geen code

### ISSUE THREAD

**Issue by marloVGulik** [MarijnvSprundel/easybingo#1]
Ik zie geen code

**Comment by MarijnvSprundel** [comment]
Wauw! Onprofessioneel!!!! Je moet je sociale normen niet op mijn GitHub repository toepassen de heer Marrel van Zuid-Delft de 4de! Ik zal het hoge gerechtshof in Den Zaagsel toelichten op deze ketterlijke opmerkingen.

Met vriendelijke groet,

Marijn van Sprundel
